# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-ddns-secret
    namespace: networking
type: Opaque
stringData:
    CF_USER: ENC[AES256_GCM,data:edtqs1nEcfjR64H5uy16ECleJfEyQjfZ,iv:SivB0jxjWFFMnoxxcZyj87hp6QhVLoyWxPrL2q0ujwQ=,tag:WixukEgFlsUQKCbP6SRbJg==,type:str]
    CF_APIKEY: ENC[AES256_GCM,data:FsDG2XVWReVhcxu1JCfU+/gJ+OQUfKfVtDOjQWUEklqZAwxnKw==,iv:I0R0zUdiVluhhvabXZJJf0gYMfqc0AJA1TjB734ahlg=,tag:eSf7+HYke9vxIwbK0wnVFQ==,type:str]
    CF_HOSTS: ENC[AES256_GCM,data:G6ZD3P9fBLTaVtNVbn2CmM4=,iv:HGZVGDaxS01GGVsTuOZVlNWv0HxM0nOU1u4LbYiBqLc=,tag:e8Hgq48XsoNxk++pQtLuzg==,type:str]
    CF_ZONES: ENC[AES256_GCM,data:urIKC6UlGEuwitED/61y12EiowSaIBI=,iv:vXqfUakp8ObsnDxljclDd5PcqHCH7imQVeX9ukiVxvk=,tag:QN3as765UMpJO8bNY/gN4A==,type:str]
    CF_RECORDTYPES: ENC[AES256_GCM,data:Eg==,iv:eNyLUQd/H/ti7r74Y+Nd8wfU6lmjrq8PlSPSLT0bYbQ=,tag:tK2WMyNfSlPdyk781A8WBg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wzxpy3cmcktm6554flrp6jnwdtxeceg3433fvsahnhem4gfudytqdkgleq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOSE85SVI2YW55QVdvNmhX
            TEpid3F6MGtPQlBzVEVzRFUvTnBEOVNjWDI0CjQvNDlNMzNKWko0K3BkR1lOMWJF
            RmdXSHprTVYxK3Z5RlRLRTYrSmo4VWMKLS0tIG5qNUN0TlRlOVZVWEczTkJReVBw
            ZXBnamdPdHpvbUtmaU5xNHQ4c2RleEEKIEBhHYIeFuweK4UJCbBwLzf6Pn5ovX/6
            jg+pZB3eXz0eQ6vQUUNq16iu2I32IwauhoCTS/7TR75p7XK8jF14ag==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-25T18:04:43Z"
    mac: ENC[AES256_GCM,data:z+OjbghflDb4rHel8oZjustycMiwbRbqxPaZoEJyiOIpozULqoxWcWuc+gRf1Xs2u5lIZ6nUGxoJ+iF5w1yJ1cIQIKTGOrfpfzvsPOwiOgOCNpwtsq7ZdNSFfhJRNSMyApot7YhyZkBg5Jrh/FrnqG6S9cTnFveVDH/Jh9HEs58=,iv:Is0biTnBzdxh4ddxdF39vSdwfULyDZP7Ny28XyqV6v0=,tag:4WP9Cpr4EYppnBb5lij7nQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
