apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: networking
resources:
    # - ./audiobookshelf
    # - ./authelia
    # - ./bazarr
    # - ./calibre-web
    - ./external-services
    # - ./gotify
    # - ./grafana
    # - ./immich
    # - ./kopia
    # - ./lidarr
    # - ./longhorn
    # - ./nextcloud
    # - ./overseerr
    # - ./paperless
    # - ./plex
    # - ./prowlarr
    # - ./radarr
    # - ./radicale
    # - ./readarr
    # - ./sabnzbd
    # - ./sonarr
    # - ./syncthing
    # - ./tautulli
    # - ./traefik
    # - ./vaultwarden
