# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: home-assistant-secret
type: Opaque
stringData:
    HASS_ELEVATION: ENC[AES256_GCM,data:TQPa,iv:6//S8JNZmTuIdLdF0uBBJWb9fDQT0eEitwbT9IEbrTs=,tag:bZN3fA2HKlF4iEOs00vo5A==,type:str]
    HASS_LATITUDE: ENC[AES256_GCM,data:gbFb4DfVfgHD+OHhsZyUph4=,iv:SDfxusWBnesoUCyM0PPBvmmqU9vd/3cKsROlKyBw9Sw=,tag:2I4ws2CV3+f6YD3UKZKv9g==,type:str]
    HASS_LONGITUDE: ENC[AES256_GCM,data:B1GZsK2UTwxw5XuAbsTMrYw=,iv:w0sVp5sQ1Ojb8ANuARwpCrjnLrYMF7Z9eA9aLm6NTh4=,tag:90RRiXeQu+wdOmAprcFQHw==,type:str]
    HASS_POSTGRES_URL: ENC[AES256_GCM,data:RXBmPrxIoLu/9xPct7RrbF5pcM6i7QBudSAc5+kqYuA1euFFyuC5LDLBA26j96zTQZIwCWmtLyMvixaaU1PTC0tx2AZd1TAte42XO2SQdC2Wt8hDOS6Sj1aE3HHoLCF+cE4XoKiyp0OLrGUhHHHHl5M=,iv:FORSM2oxkJLb2fAvySaxnnmG5fZ95nrwE1iPmwUIOsM=,tag:ZozKrITvJxc8v9OoKuPHVQ==,type:str]
    #ENC[AES256_GCM,data:9KvvhyJiakwR7C1h2dI=,iv:mrTXsdXeVYqsgSjjvO42D4d3EOiJkYL2FvqWETpMfKg=,tag:jAszKvw46kWz497pOvsBdQ==,type:comment]
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:1SRNKSBPPqyZEmp82dQ=,iv:RnTUjDm3nqnsczDQRdyItTPGTFr4HGq6Y4JQF9Av9Gk=,tag:6zmGkztLnHcJ5jZSZ2r4Kg==,type:str]
    INIT_POSTGRES_HOST: ENC[AES256_GCM,data:jwzsHtgDErFa/GkPxbwhXXnH4psjkZTGNG7q96Gh2L+Gaj7iA/cs,iv:SctcghrLMd8DOT4LLFHaLFL1+cHBmTpym5lKP91jfYc=,tag:WMXQXPjQx86riOlI/bz+Cg==,type:str]
    INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:iqrJE3+uPZagosCvcKBNMKDXbQv8TmfLPhTgvebdAqBppNocQoV6+A==,iv:pkCw7JOKFw3F74glJ67jUQ+j2QHp1CFYzYWeJ/pX7/4=,tag:lFmlpPZm6xu5hlQ4FNNd6A==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:u4MwDos3l73h/R5u1ZOU45X7Om5ozng+0w5Frqpn,iv:XwHisbUZsxCr+vYB6Su7s/p8TNE1z5xTZBpV2U2cz54=,tag:g8/0KGT6KoTUeCW3AbxhTw==,type:str]
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:ab2x8b4LPapb/o7XCPQ=,iv:4Q1ndwCDzP3b/Ld/W4gw6Z09src2doKf27hicpfonS8=,tag:tVkhEA9V6d+LVG/NVAsEgA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wzxpy3cmcktm6554flrp6jnwdtxeceg3433fvsahnhem4gfudytqdkgleq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGZmg2b1JXUUwraGJtd01S
            bGJ4QlduR05weXpPTGpGeGtqRHU1UVQ3S0JvClhwNlhrVGdVSDlyVmFySSsvR3hm
            WDd5dzlncHRYZmJaS0JMbkRwaldGUUEKLS0tIGJsYkdSZ3ZTQkpINUIzVGlQV1cr
            OWVGY0JDTXM1NzNudElVL2liYmtyMFEK2cHS9x2ZpO0DIcBBTyCXe1kGuQsbfhUM
            12eRmulKLk+Xt8cES6O+lDseglRjw58a+TEIMFPAesf2Y22op2ZM4g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-20T18:58:28Z"
    mac: ENC[AES256_GCM,data:q7RP58rCj9fdVM5En/4cPJBbN1c9SeVC1hQafDBvBTYyf1ZJoZD943F2LNIY8wUdy0zS7Hjumq3WflCSN0Tlo2w7HOwwICpwfPOlSiWuYn6dQQVILf390+yw8LT2eRSLJDcJGin78+ZIl7q1d0hxsrp1lN184GgYJN8d2atWRgY=,iv:zXNvJIN5V/Szv+p10kuZSgGsIGYzEQLit0BApnmIysA=,tag:bzyAGvVR7W254MfkXKApAA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
