---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: networking
resources:
  - ./authelia.yaml
  - ./flux-webhook.yaml
  - ./secure-headers.yaml
  - ./nextcloud-redirect.yaml
  - ./local-only.yaml
