---
# yaml-language-server: $schema=https://raw.githubusercontent.com/JJGadgets/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-kubernetes-replicator
  namespace: flux-system
spec:
  targetNamespace: kube-system
  path: ./kubernetes/apps/kube-system/kubernetes-replicator/app
  sourceRef:
    kind: GitRepository
    name: home-ops-kubernetes
  interval: 30m
  prune: true
  wait: true
