---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: tandoor-secret
spec:
  target:
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        # App
        POSTGRES_HOST: &dbHost postgres16-rw.databases.svc.cluster.local
        POSTGRES_PORT: "5432"
        POSTGRES_USER: &dbUser "{{ .TANDOOR_POSTGRES_USER }}"
        POSTGRES_PASSWORD: &dbPass "{{ .TANDOOR_POSTGRES_PASSWORD }}"
        POSTGRES_DB: tandoor
        SECRET_KEY: "{{ .TANDOOR_SECRET_KEY }}"
        DB_ENGINE: django.db.backends.postgresql_psycopg2
        SOCIALACCOUNT_PROVIDERS: |
          { "openid_connect": { "SERVERS": [ { "id": "tandoor", "name": "Authelia", "server_url": "https://authelia.${SECRET_DOMAIN}/.well-known/openid-configuration", "token_auth_method": "client_secret_basic", "APP": { "client_id": "tandoor", "secret": "{{ .TANDOOR_OAUTH_CLIENT_SECRET }}", } } ] }}
        # Postgres Init
        INIT_POSTGRES_DBNAME: tandoor
        INIT_POSTGRES_HOST: *dbHost
        INIT_POSTGRES_USER: *dbUser
        INIT_POSTGRES_PASS: *dbPass
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
  data:
    - secretKey: TANDOOR_SECRET_KEY
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: a7bb0a86-14c7-4748-9d35-2d425dc2180b
        property: secret_key
    - secretKey: TANDOOR_POSTGRES_USER
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: a7bb0a86-14c7-4748-9d35-2d425dc2180b
        property: pg_user
    - secretKey: TANDOOR_POSTGRES_PASSWORD
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: a7bb0a86-14c7-4748-9d35-2d425dc2180b
        property: pg_password
    - secretKey: POSTGRES_SUPER_PASS
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: 2ad3fcad-e666-4701-b44c-a4e6e5cc5da3
        property: password
    - secretKey: TANDOOR_OAUTH_CLIENT_SECRET
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: a7bb0a86-14c7-4748-9d35-2d425dc2180b
        property: oauth_client_secret
