---
apiVersion: gateway.networking.k8s.io/v1
kind: SecurityPolicy
metadata:
  name: 'authelia-extauthz-dispatcharr'
spec:
  targetRefs:
    - kind: HTTPRoute
      name: dispatcharr
  extAuth:
    headersToExtAuth:
      - 'accept'
      - 'cookie'
      - 'authorization'
      - 'header-authorization'
      - 'x-forwarded-proto'
    failOpen: false
    http:
      backendRefs:
        - group: ""
          kind: Service
          name: authelia
          namespace: default
          port: 9091
      path: '/api/authz/ext-authz/'
      headersToBackend:
        - Remote-User
        - Remote-Groups
        - Remote-Name
        - Remote-Email
