---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  NAS_ADDR: 192.168.20.5
  MEDIADIR: /spool/media
  BACKUPDIR: /spool/backup
  DOWNLOADDIR: /spool/media/downloads
  TZ: "Europe/Berlin"

  #Metallb
  SVC_MQTT_ADDR: 192.168.178.222
  SVC_HASS_ADDR: 192.168.178.250
  SVC_PLEX_ADDR: 192.168.178.224
  SVC_LLDAP_ADDR: 192.168.178.225
  SVC_OPENHAB_ADDR: 192.168.178.226
  SVC_Z2M_ADDR: 192.168.178.227
  SVC_JELLYFIN_ADDR: 192.168.178.228
  SVC_POSTGRES_ADDR: 192.168.178.230
  SVC_SMTP_RELAY_ADDRESS: 192.168.178.233

  CLUSTER_CIDR: 10.42.0.0/16
  KUBE_VIP_ADDR: 192.168.20.9
  NODE_CIDR: 192.168.178.0/24
