---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: postgres-adventurelog
  namespace: databases
  labels:
    kustomize.toolkit.fluxcd.io/namespace: databases
spec:
  name: adventurelog
  owner: adventurelog
  cluster:
    name: postgres
  extensions:
    - name: postgis
    - name: postgis_topology
    - name: fuzzystrmatch
    - name: postgis_tiger_geocoder
