---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # - ./secret.sops.yaml
  - ./helmrelease.yaml
  - ./pvc.yaml
configMapGenerator:
  - name: pmm-config
    files:
      - configs/config.yaml
  - name: pmm-tv
    files:
      - configs/tv.yaml
  - name: pmm-movies
    files:
      - configs/movies.yaml
  # - name: pmm-scripts
  #   files:
  #     - ./scripts/run.sh
generatorOptions:
  disableNameSuffixHash: true
  annotations:
    kustomize.toolkit.fluxcd.io/substitute: enabled
