---
# yaml-language-server: $schema=https://datreeio.github.io/CRDs-catalog/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: matterbridge
spec:
  components:
    - ../../../../components/volsync/local
  dependsOn:
    - name: multus-networks
      namespace: networking
    - name: volsync
      namespace: volsync-system
  interval: 1h
  path: ./kubernetes/apps/default/matterbridge/app
  postBuild:
    substitute:
      APP: matterbridge
      VOLSYNC_CAPACITY: 1Gi
      VOLSYNC_PGID: "0"
      VOLSYNC_PUID: "0"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: default
  wait: false
