---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: kometa-secret
spec:
  target:
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        KOMETA_PLEX_API_KEY: "{{ .PLEX_TOKEN }}"
        KOMETA_TRAKT_CLIENT_ID: "{{ .TRAKT_CLIENT_ID }}"
        KOMETA_TRAKT_CLIENT_SECRET: "{{ .TRAKT_CLIENT_SECRET }}"
        KOMETA_TRAKT_ACCESS_TOKEN: "{{ .TRAKT_ACCESS_TOKEN }}"
        KOMETA_TRAKT_REFRESH_TOKEN: "{{ .TRAKT_REFRESH_TOKEN }}"
        KOMETA_TRAKT_EXPIRES_IN: "{{ .TRAKT_EXPIRES_IN }}"
        KOMETA_TRAKT_CREATED_AT: "{{ .TRAKT_CREATED_AT }}"
        KOMETA_TMDB_API_KEY: "{{ .TMDB_API_KEY }}"
        KOMETA_MDBLIST_API_KEY: "{{ .MDBLIST_API_KEY }}"
        KOMETA_OMDB_API_KEY: "{{ .OMDB_API_KEY }}"
        KOMETA_TAUTULLI_API_KEY: "{{ .TAUTULLI_API_KEY }}"
        KOMETA_RADARR_API_KEY: "{{ .RADARR_API_KEY }}"
        KOMETA_SONARR_API_KEY: "{{ .SONARR_API_KEY }}"
  data:
    - secretKey: PLEX_TOKEN
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 3a2aa0ba-39ad-4b7e-b0c3-8861d16a56d0
        property: token
    - secretKey: TRAKT_CLIENT_ID
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 106e86ce-9d9b-4b19-b706-45acbc9bcdb2
        property: clientid
    - secretKey: TRAKT_CLIENT_SECRET
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 106e86ce-9d9b-4b19-b706-45acbc9bcdb2
        property: clientsecret
    - secretKey: TRAKT_ACCESS_TOKEN
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 106e86ce-9d9b-4b19-b706-45acbc9bcdb2
        property: accesstoken
    - secretKey: TRAKT_REFRESH_TOKEN
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 106e86ce-9d9b-4b19-b706-45acbc9bcdb2
        property: refreshtoken
    - secretKey: TRAKT_EXPIRES_IN
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 106e86ce-9d9b-4b19-b706-45acbc9bcdb2
        property: expiresin
    - secretKey: TRAKT_CREATED_AT
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 106e86ce-9d9b-4b19-b706-45acbc9bcdb2
        property: createdat
    - secretKey: TMDB_API_KEY
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: a8c9edb9-e52c-4c7e-ba22-957fcb039501
        property: apikey
    - secretKey: MDBLIST_API_KEY
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 8c8fd293-664c-4bf7-91b7-0ed6d9e90bb9
        property: apikey
    - secretKey: OMDB_API_KEY
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 1ac0ed4a-aac5-47e2-a0e0-8aff0f7766eb
        property: apikey
    - secretKey: TAUTULLI_API_KEY
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 3d4cdfbb-3ce2-4857-83c6-a79a02021374
        property: token
    - secretKey: SONARR_API_KEY
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 68225868-4b24-49f0-8d04-60d6a80bc652
        property: token
    - secretKey: RADARR_API_KEY
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 133e1c1d-894d-4fc7-a69c-d44bd3fe090f
        property: token
