---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: paperless-secret
spec:
  target:
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        # App
        PAPERLESS_ADMIN_USER: "{{ .PAPERLESS_ADMIN_USER }}"
        PAPERLESS_ADMIN_PASSWORD: "{{ .PAPERLESS_ADMIN_PASS }}"
        PAPERLESS_SECRET_KEY: "{{ .PAPERLESS_SECRET_KEY }}"
        PAPERLESS_DBPASS: "{{ .PAPERLESS_POSTGRES_PASS }}"
        PAPERLESS_DBHOST: &dbHost postgres16-rw.databases.svc.cluster.local
        PAPERLESS_SOCIALACCOUNT_PROVIDERS: |
          { "openid_connect": { "APPS": [{"provider_id": "authelia","name": "Authelia","client_id": "paperless","secret": "{{ .PAPERLESS_OAUTH_CLIENT_SECRET}}","settings": { "server_url": "https://authelia.${SECRET_DOMAIN}/.well-known/openid-configuration"}}]}}
        PAPERLESS_APPS: allauth.socialaccount.providers.openid_connect
        # Postgres Init
        INIT_POSTGRES_DBNAME: paperless
        INIT_POSTGRES_HOST: *dbHost
        INIT_POSTGRES_USER: "{{ .PAPERLESS_POSTGRES_USER }}"
        INIT_POSTGRES_PASS: "{{ .PAPERLESS_POSTGRES_PASS }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
  data:
    - secretKey: PAPERLESS_ADMIN_USER
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: 6dad7c46-0bce-4768-93ce-97b7ee5f83cd
        property: username
    - secretKey: PAPERLESS_ADMIN_PASS
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: 6dad7c46-0bce-4768-93ce-97b7ee5f83cd
        property: password
    - secretKey: PAPERLESS_SECRET_KEY
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 6dad7c46-0bce-4768-93ce-97b7ee5f83cd
        property: secret_key
    - secretKey: PAPERLESS_POSTGRES_USER
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 6dad7c46-0bce-4768-93ce-97b7ee5f83cd
        property: pg_user
    - secretKey: PAPERLESS_POSTGRES_PASS
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 6dad7c46-0bce-4768-93ce-97b7ee5f83cd
        property: pg_password
    - secretKey: PAPERLESS_OAUTH_CLIENT_SECRET
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 6dad7c46-0bce-4768-93ce-97b7ee5f83cd
        property: oauth_client_secret
    - secretKey: POSTGRES_SUPER_PASS
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: 2ad3fcad-e666-4701-b44c-a4e6e5cc5da3
        property: password
