# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: lidarr-secret
type: Opaque
stringData:
    LIDARR__POSTGRES_HOST: ENC[AES256_GCM,data:a9fdP6uVS3ssUeigNHqSukvtaXe3WvJIRfVc92S7K5Wn5x1bZ6a7,iv:P6r4V/WrxrFXywNXsQ/wRMQhRoyLbqQWBtXOohirXAY=,tag:gOgVDyu11i+JgXtOfIlllg==,type:str]
    LIDARR__POSTGRES_PORT: ENC[AES256_GCM,data:NrRrvQ==,iv:2MNSVOYwmdp0Zhzeagkw3ZXtK8Rgds4gOYcI4CzP53g=,tag:KMMh8/M0cRWPMzb+6yoKvA==,type:str]
    LIDARR__POSTGRES_USER: ENC[AES256_GCM,data:u6EgmJle,iv:4e/PFt7wOU3SdwTD85hXwxYSnNxg94XvhK+zYWxFil0=,tag:UuTXrf/s1DCZHljsc0ZCMA==,type:str]
    LIDARR__POSTGRES_PASSWORD: ENC[AES256_GCM,data:qBQah4jN8CH/PUXvYZD8/OU+EKuXIYVLw7AneRacp8WN9fO6,iv:4aD23Mi21CZJgHUYWO0fLRDBJJsLoPaQkYs5jxwYDl0=,tag:wt6o+NYGXc9pdsymQ9jYBA==,type:str]
    LIDARR__POSTGRES_MAIN_DB: ENC[AES256_GCM,data:DVM3MjXHosTQvsQ=,iv:4cuu/HPDvPf4oOee7nYUr3TAnUhwy/uu3cFBNBnKrmg=,tag:G8Gl8wqToWIrJB77VaEJxg==,type:str]
    LIDARR__POSTGRES_LOG_DB: ENC[AES256_GCM,data:lx+C+4IQcMi67A==,iv:b4UQ4ZEZ6IeHW3M90QcWxSr0vfLXgcNbBmahaNuNOCc=,tag:6qekKRCAVSKDeDp6g9SS1A==,type:str]
    #ENC[AES256_GCM,data:Cgk/ut5GaelFZk1aBgU=,iv:/AkJpuiNOJ4z8m5LEb1oupawsDVtq7wqJY2mSqhxZ2Y=,tag:WqSh4H1VIRstZuJyWPDzhg==,type:comment]
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:YyKSxphQHgS9dMdB+TMvWX5BCQzuAw==,iv:hJGhsbWZCOzzW4K2AL6QGogIvvoA2+IT/V/UpsVXj6I=,tag:iJqbkRGOAiBcV/J3xf5KXg==,type:str]
    INIT_POSTGRES_HOST: ENC[AES256_GCM,data:4L7wJBHHkda7Nnk4wq3YXrd8HApfNY+Ck5vh8QCVslcUxBu18+tb,iv:FIHUpmZtTJI5gxfJEVkB6myew9UiPvMVbKySpnHac8A=,tag:cTamqjob0eNvN+k3TwX0hw==,type:str]
    INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:UWG/DY4dQKsO6iu1ZWrPPg12ZOeSSaQ2Dy35nim2AJVKJeVIutsuiw==,iv:BRYZWzjB1tgBAhJENzSWP3sI2wzrh0X5apXpvXWMWT0=,tag:8Z+hYSIvp9IzXoRBHaF1vw==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:1J+ofWZhrajl6FJ/9+ninaLE2QJOHjtwmyo3PuCPykeZSbgh,iv:4aSm4nZOxafikPmeUlgp4o/fumn3mqNfj4BFkzyz+Oo=,tag:QEbwYu9XVuuD7QwuUMM/Gw==,type:str]
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:wEG9fCqF,iv:1i6EnnzunCPrFFAGfikoCYC9v4teI07MmLCgPHuC+64=,tag:pqoOVeijrwP7xCPDS9wByw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wzxpy3cmcktm6554flrp6jnwdtxeceg3433fvsahnhem4gfudytqdkgleq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkVEoxSTNYU2FPYVUxdWlO
            Rm9UTVZyODNBNytOOHhHc2VidUtPZWtzdkVvClk3TDdpZmRnUi8waEd1QkFUalNu
            UHI2R0F0WFZEelIxZW9XUEw4WkNnVEUKLS0tIFEzQ3lPZW8vNHJwNEpINzhuYS9I
            emY0TXpyQ1hzR1FZOVhSOHB5TGtwbkUKagGRF9jFail8azeiVL3+I99h1fQycoUe
            A3pSYvF4JF2PF/278T4mLM2pCm+mBF87T6u8YNpB23GaKUfwznwxhg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-20T19:02:52Z"
    mac: ENC[AES256_GCM,data:x4onX9aZah5lzDPYPcdg/+w7G2QN7qbEWq1XKq01UD4YoxiNBZXccpUpzMwpA97iQ1DvOOgMfmtJSC5r+ZnYNpTWPgwrXUQKq1a3O9YdQc1fHQjoUMAueEjUa+Z5KGitjpgbLcJlemNeVeOBekJJnfjquE8gDtfoikLn8Oy1qRo=,iv:Y+CXmKMLqRqNQ1sRBjwayuqYzb2Heu/2l2ms91HthyM=,tag:MlignceM5kiIWRx+XUukKg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
