apiVersion: v1
kind: Secret
metadata:
    name: bitwarden-cli
stringData:
    BW_HOST: ENC[AES256_GCM,data:KKjTzXfhVyASpVUSLsEs83he57rYawe5dJM=,iv:pEoPqKlbtGRm4iRIsFtN3P4e0XeRbmRRfSbqBKpeCSk=,tag:3gTI2XUi0q0x2LKAQHWxVw==,type:str]
    BW_CLIENTID: ENC[AES256_GCM,data:0EyeVn8xS9U+sf5O4ujGM+9lgLxap9OutI2Vkyc670eQs5x58QP+gkY=,iv:SQMLiOcHmmynjryqZCnAeZECmbNrTyjXS8qKVUiPPpY=,tag:ZRCxPRPJizMX1FDX2uB2ag==,type:str]
    BW_CLIENTSECRET: ENC[AES256_GCM,data:FeZgzcjMDskKQsluro9EJ29P6ekOkM8L0vM29vPP,iv:FHR0JKq67KARzxzEzBp3UU1+aYZH3KJiSb3LoyjLNDE=,tag:gfz75Fz13+WfUetIsmc5CQ==,type:str]
    BW_PASSWORD: ENC[AES256_GCM,data:vLxqJlcCRCh7EcNrikP2TJ53OoDx,iv:UqzStXo+TBRbYHWmXTTvelctZyrLyRaSfevFicsvycg=,tag:m/hHq/3GdGnxvp9CKDUL3g==,type:str]
    BW_USER: ENC[AES256_GCM,data:j9XlaNSF2JKcb8o/2IkATBcR,iv:oP6J6eDcjY/7F8mHPEz24tZp3AbAeLRJngoWWNHAHI4=,tag:RGTYAgTGFzjMdHpUyIUXoQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wzxpy3cmcktm6554flrp6jnwdtxeceg3433fvsahnhem4gfudytqdkgleq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5cG1yVU5qUE9aOWhYeWVx
            R3JOdlNGOW0rcGJ3SGlJdEZRWEM0aXlwVkJVCjR6NDZkRThnd2YyUERlbGdQTGY1
            M2tZd1pkY2pjT3YyM0FyY2dwY3J1N28KLS0tIDhyK0thNjcrTUtqME1CRWwrUkdm
            SXFVVUpPTE9ZT2xLTjF1Uzk1R2NkcTgK3y0rwoGGAQQ+R/F2zgI9Y0SnR2lzEwSM
            8gpDClPKQ+lS/pAtCHWPREP3mAoO38Xq3LHUqnLy9B5TirFXy62NWA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-07-07T08:58:31Z"
    mac: ENC[AES256_GCM,data:P0HdRu9W+7ooG0WOoYMk10muNfU3FmxU4KhFssMu943Iqom+dj5gPZ+j7d3yilcJoOXeMAnBBc/py45/yXRVHdK+Ewwh/Cece3Vk454dqs7QE2bU5GUkPbA2DDyHv/jyZ+c3Itf3K3glQ06wX2XYOWbcrqQ5omwQMECc2FL9SS0=,iv:NBYgOwka5V2Mh6oHQ06EwPGrQP6mlLDe27bgZBX16/M=,tag:xQcy+6jv8Doe/gbRlDPfAA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
