# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: external-dns-cloudflare-secret
type: Opaque
stringData:
    email: ENC[AES256_GCM,data:bFA7eD0/K8PRbNE4+tNa82FBr1wSw5a8,iv:+MTS1n58V3mQIQL7bnv/7Cdwxf/qyJQntEXKdpirv0E=,tag:8sEb2W8PSIIiJzolR49rSA==,type:str]
    api-key: ENC[AES256_GCM,data:HZfc1e4ldSWEwOVwO+cbVZlrAElH8fop+TQ/Bx2jI5fgUTBuZg==,iv:2iytP9RoG3sFNs3T1mYh9CDwCG9rlJVjln1qinawyZ8=,tag:hmA7nfJ6aXDsezfzkxZBrQ==,type:str]
    api-token: ENC[AES256_GCM,data:M8Qet1Ko0jmN9nxDDXnypabZNgTxufl7QHw20nXM46x7Nggkg6x3yg==,iv:pzKy2Tf6EzsUF/WTPjctlIjrNDCcvNlLUO+PZkl3Xxs=,tag:YLpXJmMaJ48MzAMe22t7kA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wzxpy3cmcktm6554flrp6jnwdtxeceg3433fvsahnhem4gfudytqdkgleq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOSE85SVI2YW55QVdvNmhX
            TEpid3F6MGtPQlBzVEVzRFUvTnBEOVNjWDI0CjQvNDlNMzNKWko0K3BkR1lOMWJF
            RmdXSHprTVYxK3Z5RlRLRTYrSmo4VWMKLS0tIG5qNUN0TlRlOVZVWEczTkJReVBw
            ZXBnamdPdHpvbUtmaU5xNHQ4c2RleEEKIEBhHYIeFuweK4UJCbBwLzf6Pn5ovX/6
            jg+pZB3eXz0eQ6vQUUNq16iu2I32IwauhoCTS/7TR75p7XK8jF14ag==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-21T21:38:42Z"
    mac: ENC[AES256_GCM,data:JFU8rJnDhkATMqyRmdhgdymQEuVbmKaoYd2p3i99FFPVM1aY432g0dOpGPVuc/Gfit2/k+zgV2OroJRu1PYSGoAUHqb3VRpBtpdDTtEi6GqCzZwRiGMklNB5sJVmAoTNvuaFsoX/ASzugXHfYUEkF7PDtDSr0eA2u2CK7Mplq9M=,iv:ZLdNUgyGm5l1dq9R39RsQvdsG2lOGZYS0awIuwx3a60=,tag:j5+/HeOvTIQZHcPwMKGWFA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
