apiVersion: v1
kind: Secret
metadata:
    name: paperless-secret
stringData:
    PAPERLESS_ADMIN_USER: ENC[AES256_GCM,data:eQCwDSbWTg==,iv:1xbe/2UjDJO6yEsB3pio8W1CSZl1tNlVtVeupMmd1hs=,tag:mD0PaUPK2YHiA9DqeVL3Ww==,type:str]
    PAPERLESS_ADMIN_PASSWORD: ENC[AES256_GCM,data:U8X4pBIGuZboUn4KNVXLwc8+QrPqapD7h7waY2hUfu+oumridnTnnfmPHhKOSA==,iv:Ly3hKRbiOvn6E2qWZ3UQ9KDVt3HoUqYDTVGCfp5m3PE=,tag:QnzLM7+iwuAwu5bo+J6m2w==,type:str]
    PAPERLESS_SECRET_KEY: ENC[AES256_GCM,data:tey9CrQbtjrNEddj0msX0pv0L5xMH9BIe5TyPm/u,iv:tgBNCQ43v53FcTrrtxBMLhbR5Cfp9eRutXNRc2fq8yk=,tag:qc8cgg4vEc6I8hbXs0jfMA==,type:str]
    PAPERLESS_DBPASS: ENC[AES256_GCM,data:YLaWgxmMqdDn7gf788gckj2kWbEBwW2K8pwLWUs2caZOpA48b8AZ2l5OcbM=,iv:CK8QqpQDOyUTf8Y6SBpbsdvPT0GegjBb9qdLKoY8sa0=,tag:kY9tWnXlCzf40QjpNb6Y0g==,type:str]
    #ENC[AES256_GCM,data:mY0VXG2fn2Hi5FWndcE=,iv:Owy2ETrYA7z0D9TOSzBqnW8+1tKonQ+vZyZb/pS8tJ4=,tag:apgb9I9/Ej1EXwQL+fob6g==,type:comment]
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:bX6j5drn3xsK,iv:JU22F6lhgnemnwxBRKMDZ2OyofeqOmEhhCm/L38tarE=,tag:q5aXvmX3/IHnbP3YH+B0WA==,type:str]
    INIT_POSTGRES_HOST: ENC[AES256_GCM,data:z0zQPWDN3JvEV2F5oVrABewIhUVHWcRRgZprgqFHb2I3sgRmrhof,iv:3wfdPOs1fR2ufpR77ukUiYSr2HTc0wZRbSVbYHNdRSg=,tag:Vg1c0VT0QgZV4L63TI57xQ==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:GEh4wtAFgPyOcZwpAX0cfFoikYzbaitYpYn/KyiUR3uIcf2j/4bdR7kddlY=,iv:/m2JZfmoES8REaAnkEAsmd3Cm0BRM4fZu/mAaxZINEs=,tag:pzto28b77Bdvl1nXD/oQTw==,type:str]
    INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:CiiYWK9CnPkSQ/N5lG5ocMFRpjBvBDP48nK+OC2cZY8fN6URxC1oGQ==,iv:PVI09NrWd3M7FGgl0OLv2SVPfvAQ77WntAYUjQcKWuc=,tag:MQIKOYIiFei+rwv4Zeo5Pg==,type:str]
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:3h5l4K1wzFd0,iv:9Y5WsHgGaj7xgp31T9sS6+dqk7qiIcPC4kO7/ax3jtk=,tag:202QgfmYgvdmVJOXFJYFFg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wzxpy3cmcktm6554flrp6jnwdtxeceg3433fvsahnhem4gfudytqdkgleq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsRXVyNWNBMHUxdWxhdWxI
            amRWN3RZRXd5NndSSTJEdjYvMGptRVdCV1NzCk9mN2JTbHFzVTdGTjNpNlNjWUxs
            Y0xVb2lxeFV6UDhuckxYTG4wZFBDVTgKLS0tIGlIMGNMMWRERGZYSmZvaHVXMlNk
            dGpub09nU1NQVmc2OWRraERZWmp2enMKDyiFTdgGyzJSPPSPDanibXj5x23nVtA3
            fdBG+WKX9cInnueaYh3jlgQEyxa40hFxDnSA1U3v6pApSSSH6gH4GA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-20T19:06:11Z"
    mac: ENC[AES256_GCM,data:8r572lN43Jj3/BH9QJJE8A5DzbJhpoqpp8Ek4fdT0wqHUiG3kjNGEU4rWxHygCgIL9TbZ7G38DepIgRQekKYTmZO2YqYX25cm6lytaPG+aOGu0QNm8EAUOK6brf0ceMu4IBU1ikshh551kNWnhFJbh4gMaXROyGejxIi7eFZsrU=,iv:fk3u7nNkU4my+YoNiaxnbFLCrZ+7fejEceeLN/PMNfQ=,tag:GFD2JmFO81UW/BQkb1yszQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
