---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/gateway.networking.k8s.io/httproute_v1.json
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: minio-s3
spec:
  hostnames:
    - minio.${SECRET_DOMAIN}
    - s3.${SECRET_DOMAIN}
  parentRefs:
    - name: envoy-external
      namespace: networking
  rules:
    - backendRefs:
        - name: minio-s3
          namespace: networking
          port: 9000
