---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: kube-prometheus-stack-secret
spec:
  target:
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        objstore.yml: |-
          type: s3
          config:
            bucket: thanos
            endpoint: s3.${SECRET_HOME_DOMAIN}:443
            access_key: {{ .MINIO_ACCESS_KEY }}
            secret_key: {{ .MINIO_SECRET_KEY }}
  data:
    - secretKey: MINIO_ACCESS_KEY
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: ddc59a49-292c-482a-aaaf-5f43d869189d
        property: access_key
    - secretKey: MINIO_SECRET_KEY
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: ddc59a49-292c-482a-aaaf-5f43d869189d
        property: secret_key
    - secretKey: MINIO_S3_ENDPOINT
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: ddc59a49-292c-482a-aaaf-5f43d869189d
        property: s3_endpoint
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: alertmanager-secret
spec:
  target:
    name: alertmanager-secret
    template:
      templateFrom:
        - configMap:
            name: alertmanager-config-tpl
            items:
              - key: alertmanager.yaml
  data:
    - secretKey: PUSHOVER_USER_KEY
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: b4442e5a-d7ee-4cb4-8205-a91eeed53b08
        property: user_key
    - secretKey: ALERTMANAGER_PUSHOVER_TOKEN
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: b4442e5a-d7ee-4cb4-8205-a91eeed53b08
        property: alertmanager_api_token
